volumes:
  pg_volume:

networks:
  watereminder_bot:
    driver: bridge

services:
  pg:
    image: postgres:17-alpine
    restart: always
    env_file:
      .env
    ports:
      - "54320:5432"
    volumes:
      - pg_volume:/var/lib/postgresql/data/
    networks:
      - watereminder_bot

  migrator:
    build:
      context: .
      dockerfile: migration.dockerfile
    restart: on-failure
    environment:
      DB_HOST: pg
    depends_on:
      - pg
    networks:
      - watereminder_bot

  bot:
    build:
      context: .
      dockerfile: dockerfile
    restart: always
    env_file:
      .env
    volumes:
      - ./logs:/workdir/logs
    networks:
      - watereminder_bot
