name: CD

on:
  workflow_dispatch:

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "water_bot"
  CONTAINER_NAME: "water_bot-cont"

jobs:
  deploy-image:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to cloud via SSH action
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: REGISTRY, IMAGE_NAME, GITHUB_SHA, CONTAINER_NAME
          script: |
            #Setup variables
            TAG_NAME=$(echo $GITHUB_SHA | head -c7)

            #Login into Registry
            docker login -u ${{ secrets.REGISTRY_USERNAME }} -p ${{ secrets.REGISTRY_PASSWORD }} ${{ env.REGISTRY }}

            #Stop and remove old container
            docker stop ${{ env.CONTAINER_NAME }}
            docker rm ${{ env.CONTAINER_NAME }}

            #Run new container
            docker run -d -p 55001:55001 --name ${{ env.CONTAINER_NAME }} -t ${{ env.REGISTRY }}/${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_NAME }}:$TAG_NAME