name: CD

on:
  workflow_dispatch:

env:
  REGISTRY: "ghcr.io"
  IMAGE_NAME: "water_bot"

jobs:
  deploy-image:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Create .env files from secrets
        run: |
          echo '${{ secrets.ENV_FILE_CONTENT }}' > .env

      - name: Copy docker-compose.prod.ymal to the target server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose.prod.yaml,.env"
          target: ~/deploy/${{ env.IMAGE_NAME }}

      - name: Deploy via SSH (with Compose)
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: IMAGE_NAME, GITHUB_SHA
          script: |
            # Change to deployment directory
            cd ~/deploy/${{ env.IMAGE_NAME }}

            # Pull latest images
            docker compose pull

            # Set environment variables
            export VERSION_TAG=$(echo $GITHUB_SHA | head -c7)
            export IMAGE_NAME=${{ env.IMAGE_NAME }}
            export REGISTRY_USERNAME=${{ secrets.REGISTRY_USERNAME }}

            # Start or recreate containers
            docker compose up -f docker-compose.prod.yaml -d --force-recreate

            # Clean up unused resources
            docker system prune -f